[tools]
# Stack
node = "latest"
pnpm = "latest"

# Tools
fnox = "latest"

[settings]
# Enable extra features
experimental = true
# Consume Node.js version from .nvmrc, .tool-versions, etc.
idiomatic_version_file_enable_tools = ["node"]

[tasks.dev]
run = "node --watch ./build.mjs --watch"

[tasks.build]
run = "pnpm exec vsce package"

[tasks.publish]
run = "fnox exec -- pnpm exec vsce publish"
depends = "build"