# Makefile

layers:
  runtime:
    base:
      - punctuation.separator.key-value.makefile

    control:
      - entity.name.function.target.makefile
      - keyword.control.@.makefile
      - constant.character.escape.continuation.makefile

    effect:
      - meta.scope.prerequisites.makefile

    access:
      - source.makefile
